/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE = 4;
  /** RegularExpression Id. */
  int RIGHT = 5;
  /** RegularExpression Id. */
  int LEFT = 6;
  /** RegularExpression Id. */
  int ROTATE = 7;
  /** RegularExpression Id. */
  int LOOK = 8;
  /** RegularExpression Id. */
  int DROP = 9;
  /** RegularExpression Id. */
  int FREE = 10;
  /** RegularExpression Id. */
  int PICK = 11;
  /** RegularExpression Id. */
  int POP = 12;
  /** RegularExpression Id. */
  int CHECK = 13;
  /** RegularExpression Id. */
  int BLOCKEDP = 14;
  /** RegularExpression Id. */
  int NOP = 15;
  /** RegularExpression Id. */
  int BLOCK = 16;
  /** RegularExpression Id. */
  int REPEAT = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int DEFINE = 19;
  /** RegularExpression Id. */
  int TO = 20;
  /** RegularExpression Id. */
  int NUMERO = 21;
  /** RegularExpression Id. */
  int DIGIT = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"MOVE\"",
    "\"RIGHT\"",
    "\"LEFT\"",
    "\"ROTATE\"",
    "\"LOOK\"",
    "\"DROP\"",
    "\"FREE\"",
    "\"PICK\"",
    "\"POP\"",
    "\"CHECK\"",
    "\"BLOCKEDP\"",
    "\"NOP\"",
    "\"BLOCK\"",
    "\"REPEAT\"",
    "\"IF\"",
    "\"DEFINE\"",
    "\"TO\"",
    "<NUMERO>",
    "<DIGIT>",
  };

}
